### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lukaspistelak** [DBeath/feedsearch#6]
hi when i import your lib:

```
ml@ML:~/projects/InfluencersAI$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from feedsearch import search
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/feedsearch/__init__.py", line 3, in <module>
    from .feedsearch import search
  File "/usr/local/lib/python3.5/dist-packages/feedsearch/feedsearch.py", line 107
    coerced_url: str = coerce_url(url)
               ^
SyntaxError: invalid syntax
```

I installed the lib by pip:

`sudo pip3 install feedsearch
`

**Comment by DBeath** [comment]
Hi, I didn't originally write this library to support Python 3.5, it only supported 3.6 and above.

However, I had some time today and the only real issue with 3.5 support was the Syntax error because of the type hints, so I've pushed an update to make those compatible with 3.5. If you download the latest version it should work for you now.

Cheers.
